[package]
name = "preimages"
version = "0.1.0"
edition = "2021"

[dependencies]
reth-db.workspace = true
reth-db-api.workspace = true
anyhow.workspace = true
alloy-primitives.workspace = true
clap = "4.5.23"
